---
title: "AirBNBFinalAnalysis"
author: "Max Ellingsen"
date: "2023-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Motivations

Our topic focuses on how different policies across state's effect the overall price of short term rentals such as AirBnB. Our motivation for the topic revolves around recent policy suggestions pertaining to short term rentals in Bozeman, Montana.

# Data Construction

The data that we have gathered consists of many cities spread across a majority of states in the US and short term rental tax rates in the US. Because we wanted to encompass as many different types of cities as possible, our data covers all available data from our data source located in the U.S. and ranges across most all geographical regions. The data is primarily tourist hubs as these locations have the densest collection of AirBnB rental properties, however the available data includes several smaller cities that help provide a complete picture of how rental markets are behaving. The data sets consist of the most recent months data for 32 different cities. In our code, we manipulate this data by first importing all of the files in iteratively via .csv files we downloaded to our GitHub Repository then importing all of the data into individual data frames with the city name as the data frame title. As we complete this process, we insert each of the data frames into a list in order to reference them iteratively later. Next, we add a location column to all of the data frames as there was no prior labeling present in the imported data.This process is completed by extracting the names of the cities out of the data frames in our created list, inserting the title of the data frame via an external file, creating a repeated vector of the city name, then appending it to the data frame within the list. This makes the final merged data usable and was a crucial step of our process. Finally, after each data frame had added a column with their location, we bound the data frames together into our "final" tidy data set using a do.call and finalized with the general cleaning process.

After merging the data frames together, we took out the all columns we knew we would not be exploring, erring on the side of caution and leaving in more than was realistically necessary as we were still in the exploratory phase of our research. The units in our data are primarily numerical and act as counts of values. An example of this would be the minimum nights variable tracking the minimum number of nights the short term rental must be rented per listing. When looking for missing data, our data set was initially very clean and did not require much, if any, cleaning for the columns we were interested in exploring. Some columns did have missing or NA values, but those columns were of little import. We chose not to remove any extreme data as there were not any points that were taking away from the findings of our research and all points thus far have seemed to contribute appropriately. The extreme values in our data set are important to retain as they help encapsulate the entire market of AirBnB, a company that has accumulated much ill will in the eyes of the public and policy makers alike. To remove these extreme examples takes away much of the absurdity that kindles this dissent, thus painting an incomplete picture.

# Data Exploration

After importing and cleaning our data we were able to make several interesting findings, starting with a bar plot that shows the mean prices of a short term rental in increasing order. At one end of the spectrum we have Rochester where the mean price of a rental is just over 100 dollars per night whereas on the other end of the spectrum we have Hawaii where the mean price of a rental is over 500 dollars per night. This drastic difference is just one small piece into what we are looking to investigate and helps us determine where each individual city sits on the spectrum. This graph was primarily used to better understand our data set better in a visual way.

After looking at the preliminary chart we began to focus on policies that impact the prices of short term rentals. To begin this process, we created a vector of the short term rental tax rates by state we found from a secondary source. We unfortunately had to do this process, along with the linking of the rates with their respective state, manually as the scraping efforts were ineffective. We then made a similar bar plot as to the first bar plot we made where we display the tax rate of each state in increasing order. With the range of tax rates ranging up to as much as 15%, we new this was another great preliminary graph to add.

To further understand the role of taxing short term rentals as a preventative measure for AirBnB overpricing, we created a visualization of the relationship between tax rate and the mean price per night by location. To start, we removed all states that do not choose to tax short term rentals as we determined these states were out of the sample as we are trying to gauge the impact states saw when implementing taxes as a preventative measure for inflated prices. The datapoints were not permanently removed and will be considered in future findings. After filtering and plotting the data, a linear trend line was added for visualization purposes. The evident positive relationship is not overwhelmingly strong, but it is enough to suggest that there is a measurable increase in the price to the consumer when AirBnB renters are taxed at an elevated rate. Policy makers should consider that these taxes can provide outside benefits that the public can use, but these findings suggest that taxing short term rentals at an increased rate is hurting the consumer in the rental market and doing little to thwart homeowners for increasing their nightly rates.

Another key aspect of the rental market is the vacancy problems that arise in the market. Vacant houses benefit no one and only contribute negatively to the public. Thus, analysis as to whether or not decreased nightly rates actually correspond with lower vacancy rates was pertinent. Upon plotting the mean housing price against the average vacancy count of the listings in the data set (measured in nights per year), a marked negative relationship is observed. While the correlation is not strong, this would suggest that cheaper listing actually see more vacancy than their more expensive counterparts. This finding was incredibly interesting to us as our basic assumptions suggested that cheaper listings would see greatly increased occupancy rates. This relationship could be attributed to a discrepancy in the quality of listings at either end of the price range, with smaller abodes being less desirable for the typical short term renter and thus skewing the data away from the lower end of prices. While these findings suggest that occupancy problems in AirBnB's cannot be solved by simply decreasing the price of listings, it is hard to determine whether or not these findings are definitive.

#########
Insert new charts for restriction and license

# Conclusion

Upon analyzing the data of AirBnB short term rentals, the findings suggest that current measures have proved ineffective at decreasing the cost to consumer thus far. Furthermore, it is inconclusive as to whether or not driving the price down should be policy makers ultimate goal for alleviating stress on the housing markets as vacancy was shown to increase as prices were decreased. The city of Bozeman, a place that has seen housing prices soar, should look for alternative measures to alleviate stress on both housing vacancy and prices.
